site_name: Testing Full
site_url: https://jimraynor88.github.io/testing

theme:
  name: material
  custom_dir: overrides
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  - awesome-pages
  - section-index
  - rss
  - blogging:
      dirs:
        - posts
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - minify:
      minify_html: true
  - glightbox
  - macros
  - include-markdown
  - redirects

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: true

  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist

extra_javascript:
  - https://storage.ko-fi.com/cdn/scripts/overlay-widget.js

extra:
  social:
    - icon: fontawesome/solid/mug-hot
      link: https://ko-fi.com/invito
