name: build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: install
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-section-index
          pip install mkdocs-rss-plugin
          pip install mkdocs-blogging-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-minify-plugin
          pip install mkdocs-glightbox
          pip install mkdocs-macros-plugin
          pip install mkdocs-include-markdown-plugin
          pip install mkdocs-redirects

      - run: mkdocs gh-deploy --force
